#Define list of hosts."xrv" has a "file_system" key while "csr" doesn't.
#Netmiko can sometimes auto-discover file systems.
---
host_list:
  - name: R1
    vrf_cmd: "show running-config | section vrf_def"
    platform: ios
  - name: R2
    vrf_cmd: "show running-config vrf"
    platform: iosxr
    file_system: "disk0:"
